# -*- coding: utf-8 -*-
"""
Created on Fri May 18 11:35:04 2018

@author: mai1346
"""
import queue
import numpy as np
import pandas as pd

from abc import ABC, abstractmethod
from Event import SignalEvent

class Strategy(ABC):
    """
    Strategy is an abstract base class providing an interface for
    all subsequent (inherited) strategy handling objects.

    The goal of a (derived) Strategy object is to generate Signal
    objects for particular symbols based on the inputs of Bars 
    (OHLCV) generated by a DataHandler object.

    This is designed to work both with historic and live data as
    the Strategy object is agnostic to where the data came from,
    since it obtains the bar tuples from a queue object.
    """

    @abstractmethod
    def generate_signal(self):
        """
        Provides the mechanisms to calculate the list of signals.
        """
        raise NotImplementedError("Should implement calculate_signals()")

